# Generated by Django 6.0.5 on 2026-05-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0)),
                ('synopsis', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='dramas', to='dramas.genre')),
            ],
            options={
                'verbose_name_plural': 'dramas',
                'ordering': ['-first_air_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DramaCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('cast_order', models.IntegerField(default=999)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_entries', to='dramas.drama')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dramas.person')),
            ],
            options={
                'verbose_name_plural': 'drama cast',
                'ordering': ['cast_order', 'id'],
                'unique_together': {('drama', 'person')},
            },
        ),
    ]
