# Generated by Django 6.0.5 on 2026-05-22 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_in_my_list', models.BooleanField(default=False)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='dramas.drama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'drama')},
            },
        ),
    ]
